Julia Primer

In [1]:
x=6
println("x = ", x)

x = 6


In [2]:
y = 22
x, y = y, x
println("x = ", x, ", y = ", y)

x = 22, y = 6


In [3]:
myPi = BigFloat(pi,precision=128)

3.141592653589793238462643383279502884195

In [4]:
x = 1
println("x = ", x, ", size = ", sizeof(x), ", type = ", typeof(x))
y = 1.0
println("y = ", y, ", size = ", sizeof(y), ", type = ", typeof(y))
z = x + y
println("z = ", z, ", size = ", sizeof(z), ", type = ", typeof(z))

x = 1, size = 8, type = Int64
y = 1.0, size = 8, type = Float64
z = 2.0, size = 8, type = Float64


In [5]:
mutable struct Point
    x::Int8
    y::Int8
end

mutable struct AltPoint
    x::Int8
    y::Float64
end

In [6]:
p1 = Point(3, 10)
println("p1.x = ", p1.x, ", p1.y = ", p1.y, ", size = ", sizeof(p1))

p1.x = 3, p1.y = 10, size = 2


In [7]:
p2 = p1
println("p2.x = ", p2.x, ", p2.y = ", p2.y, ", size = ", sizeof(p2))
p2.y = 101
println("p2.x = ", p2.x, ", p2.y = ", p2.y, ", size = ", sizeof(p2))
println("p1.x = ", p1.x, ", p1.y = ", p1.y, ", size = ", sizeof(p1))
#mutable

p2.x = 3, p2.y = 10, size = 2
p2.x = 3, p2.y = 101, size = 2
p1.x = 3, p1.y = 101, size = 2


In [8]:
ap = AltPoint(3, pi)
println("ap.x = ", ap.x, ", ap.y = ", ap.y, ", size = ", sizeof(ap))
#byte align

ap.x = 3, ap.y = 3.141592653589793, size = 16


In [9]:
x = [3, 4, 5]

3-element Vector{Int64}:
 3
 4
 5

In [10]:
x = [3.0, 4, 5]

3-element Vector{Float64}:
 3.0
 4.0
 5.0

In [11]:
range(1, 10)
collect(range(1, 10))
collect(range(1, 19, step = 2))
collect(range(1, 10, step = 0.01))
collect(1:10)
collect(1:2:19)
collect(1:0.01:10);

In [12]:
x = Vector(1:-1:10)
#y = Vector(10:-1:1)
collect(range(-1, 1, 11))
collect(LinRange(-1, 1, 11))

11-element Vector{Float64}:
 -1.0
 -0.8
 -0.6000000000000001
 -0.39999999999999997
 -0.19999999999999996
  0.0
  0.19999999999999996
  0.3999999999999999
  0.6000000000000001
  0.8
  1.0

In [13]:
collect(enumerate(3:10))

8-element Vector{Tuple{Int64, Int64}}:
 (1, 3)
 (2, 4)
 (3, 5)
 (4, 6)
 (5, 7)
 (6, 8)
 (7, 9)
 (8, 10)

In [14]:
collect(zip(1:5, 3:6))

4-element Vector{Tuple{Int64, Int64}}:
 (1, 3)
 (2, 4)
 (3, 5)
 (4, 6)

In [16]:
A = ones(3, 2)
println(A)
B = rand(Float64,(2,3))*2 .- 1
println(B)
B*A

[1.0 1.0; 1.0 1.0; 1.0 1.0]
[0.018659256733191798 0.01870511355974891 0.520000706186903; -0.7968477701170265 0.2550873143171848 0.8651013349040679]


2×2 Matrix{Float64}:
 0.557365  0.557365
 0.323341  0.323341