In [54]:
age = 10
typeof(age)

Int64

In [55]:
first(methods(Int64), 5)  #  numai in REPL

[1] (::Type{T})(x::AbstractChar) where T<:Union{AbstractChar, Number} in Base at char.jl:50
[2] (::Type{T})(x::BigInt) where T<:Union{Int128, Int16, Int32, Int64, Int8} in Base.GMP at gmp.jl:356
[3] (::Type{T})(x::Base.TwicePrecision) where T<:Number in Base at twiceprecision.jl:243
[4] (::Type{T})(z::Complex) where T<:Real in Base at complex.jl:37
[5] (::Type{T})(x::Rational) where T<:Integer in Base at rational.jl:110

In [56]:
struct Language
    name::String
    title::String
    year_of_birth::Int64
    fast::Bool
end

In [57]:
fieldnames(Language)   # numai in REPL

(:name, :title, :year_of_birth, :fast)

In [58]:
julia = Language("Julia", "Rapidus", 2012, true)
python = Language("Python", "Letargicus", 1991, false)

Python 30, years old, has the following titles: Letargicus

In [59]:
(6 isa Int64) && (6 isa Real)

true

In [60]:
1 == 1.0

true

In [61]:
function round_number(x::Float64)
    return round(x)
end
function round_number(x::Int64)
    return x
end

round_number (generic function with 3 methods)

In [62]:
methods(round_number)

# 3 methods for generic function "round_number":
[1] round_number(x::Float64) in Main at /home/lali/TITAN-ROG-sync/julia/2021DataSci/Progs_book_2.ipynb:1
[2] round_number(x::AbstractFloat) in Main at /home/lali/TITAN-ROG-sync/julia/2021DataSci/Progs_book_2.ipynb:1
[3] round_number(x::Int64) in Main at /home/lali/TITAN-ROG-sync/julia/2021DataSci/Progs_book_2.ipynb:4

In [63]:
function round_number(x::AbstractFloat)
    return round(x)
end

round_number (generic function with 3 methods)

In [64]:
x_32 = Float32(1.1)
round_number(x_32)

1.0f0

In [65]:
Base.show(io::IO, l::Language) = print(
    io, l.name, " ",
    2021 - l.year_of_birth, ", years old, ",
    "has the following titles: ", l.title
)

In [66]:
julia

Julia 9, years old, has the following titles: Rapidus

In [67]:
function add_multiply(x, y)
    addition = x + y
    multiplication = x * y
    return addition, multiplication
end

add_multiply (generic function with 1 method)

In [68]:
return_1, return_2 = add_multiply(1, 2)

(3, 2)

In [69]:
all_returns = add_multiply(1, 2)
last(all_returns)

2

In [70]:
function logarithm(x::Real; base::Real=2.7182818284590)
    return log(base, x)
end

logarithm (generic function with 1 method)

In [71]:
logarithm(10)

2.3025850929940845

In [72]:
logarithm(10; base=2)

3.3219280948873626

In [73]:
for i in 1:10
    println(i)
end

1
2
3
4
5
6
7
8
9
10


In [74]:
n = 0
while n < 3
    global n += 1
end
n

3

In [93]:
first(methods(String), 5)  # REPL

[1] String(s::String) in Core at boot.jl:350
[2] String(v::Vector{UInt8}) in Base at strings/string.jl:53
[3] String(s::Symbol) in Base at strings/string.jl:83
[4] String(s::Base.CodeUnits{UInt8, String}) in Base at strings/string.jl:91
[5] String(v::AbstractVector{UInt8}) in Base at strings/string.jl:52

In [76]:
logarithm.([1, 2, 3])

3-element Vector{Float64}:
 0.0
 0.6931471805599569
 1.0986122886681282

In [77]:
hello = "Hello"
goodbye = "Goodbye"
hello * goodbye
join([hello, goodbye], " ")

"Hello Goodbye"

In [78]:
"$hello $goodbye"

"Hello Goodbye"

In [79]:
julia_string = "Julia is an amazing opensource programming language"
occursin("Julia", julia_string)
startswith("Julia", julia_string)
endswith("Julia", julia_string)

false

In [80]:
split(julia_string, " ")

7-element Vector{SubString{String}}:
 "Julia"
 "is"
 "an"
 "amazing"
 "opensource"
 "programming"
 "language"

In [81]:
typeof(tryparse(Int64, "123"))

Int64

In [82]:
typeof(tryparse(Int64, "abc"))

Nothing

In [83]:
return_multiple = add_multiply(1, 2)
typeof(return_multiple)

Tuple{Int64, Int64}

In [84]:
[x for x in 1:10]

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [85]:
[x for x in 0.0:0.2:1.0]

6-element Vector{Float64}:
 0.0
 0.2
 0.4
 0.6
 0.8
 1.0

In [86]:
my_vector = Vector{Float64}(undef, 10)

10-element Vector{Float64}:
 1.909796212e-313
 2.33419537056e-313
 3.39519326624e-313
 3.8195924246e-313
 4.03179200293e-313
 4.243991592e-314
 4.243991583e-314
 2.121995792e-314
 5.0e-324
 0.0

In [87]:
my_matrix = Matrix{Float64}(undef, 3, 3)

3×3 Matrix{Float64}:
 6.93771e-310  6.93771e-310  6.93771e-310
 6.93771e-310  6.93771e-310  6.93771e-310
 6.93771e-310  6.93771e-310  6.93771e-310

In [88]:
my_vector_zeros = zeros(3)

3-element Vector{Float64}:
 0.0
 0.0
 0.0

In [89]:
my_matrix_ones = ones(3, 3)

3×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [90]:
my_matrix_π = Matrix{Float64}(undef, 2, 2)
fill!(my_matrix_π, 3.14)

2×2 Matrix{Float64}:
 3.14  3.14
 3.14  3.14

In [91]:
first([x*y for x in 1:5 for y in 1:2], 3)

3-element Vector{Int64}:
 1
 2
 2